CREATE TABLE AUTHOR(
	Author_ID VARCHAR(100) not null PRIMARY KEY,
	Author_Name VARCHAR(255)
)

CREATE TABLE PUBLISHER(
	Publisher_ID VARCHAR(100) PRIMARY KEY,
	Publisher_Name VARCHAR(100)
)

CREATE TABLE BOOKS(
	Book_ID VARCHAR(100) primary key,
	Book_Name VARCHAR(100),
	Author_ID VARCHAR(100) FOREIGN KEY REFERENCES AUTHOR(Author_ID),
	price int,
	Publisher_ID VARCHAR(100) FOREIGN KEY REFERENCES PUBLISHER(Publisher_ID)
)

CREATE TABLE CREDIT_CARD_DETAILS(
	Credit_Card_Numbar VARCHAR(100) PRIMARY KEY,
	Credit_Card_Type VARCHAR(100),
	Expiry_Date DATE
)

CREATE TABLE CUSTOMER(
	customer_Id VARCHAR(100) PRIMARY KEY,
	Customer_Name VARCHAR(100),
	Street_Address VARCHAR(100), 
	City VARCHAR(100),
	Phone_Number VARCHAR(100),
	Credit_Card_Numbar VARCHAR(100) FOREIGN KEY REFERENCES CREDIT_CARD_DETAILS(Credit_Card_Numbar)
)

CREATE TABLE SHOPPING_CART(
	Shopping_Cart_ID INT PRIMARY KEY,
	Book_ID VARCHAR(100) FOREIGN KEY REFERENCES BOOKS(Book_ID),
	Price int,
	Date DATE,
	Quantity INT
)

CREATE TABLE SHIPPING_TYPE(
	Shipping_Type VARCHAR(100) PRIMARY KEY,
	Shipping_Price INT
)

CREATE TABLE ORDER_DETAILS(
	Order_ID INT PRIMARY KEY,
	customer_Id VARCHAR(100) FOREIGN KEY REFERENCES CUSTOMER(customer_Id),
	Shipping_Type VARCHAR(100) FOREIGN KEY REFERENCES SHIPPING_TYPE(Shipping_Type),
	Date_Of_Purchase DATE,
	Shopping_Cart_ID INT FOREIGN KEY REFERENCES SHOPPING_CART(Shopping_Cart_ID),
)

CREATE TABLE PURCHASE_HISTORY(
	customer_Id VARCHAR(100) FOREIGN KEY REFERENCES CUSTOMER(customer_Id),
	Order_ID INT FOREIGN KEY REFERENCES ORDER_DETAILS(Order_ID)
)